api/config/routes.rb
Api::Application.routes.draw do

  get "home/index"

  match '/auth/:provider/callback' => 'authentications#create'
  
  devise_for :users, :controllers => {:registrations => 'registrations'}

  post 'twitter/new' => 'twitter#new'
  post 'twitter/reply' => 'twitter#reply'
  post 'twitter/rt' => 'twitter#rt'
  
  resources :authentications

  resources :issues do
    member do
      get 'fix'
      get 'unfix'
    end
  end
  resources :tags

  root :to => 'home#index'

end

api/app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :provider, :uid
  
  def provider_name
      provider.titleize
  end

end

api/app/models/issue.rb
class Issue < ActiveRecord::Base
  
  attr_accessible :text, :fixed, :relevance, :address, :longitude, :latitude, :image_url, :user_id, :tweet_id

  has_and_belongs_to_many :tags
  has_many :replies
  
  has_one :user
end

api/app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :issue
end

api/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :title
  has_and_belongs_to_many :issues
end

api/app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def apply_omniauth(omniauth)
    self.screenname = omniauth['extra']['access_token'].params['screen_name']  	    	    
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
  
  def email_required?
      (authentications.empty? || !email.blank?) && super
  end
  
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

api/app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end
  
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

api/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @issues = Issue.order("updated_at DESC").limit(10)
  end

end

api/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def new
  end

  def create
    issue = Issue.create(params["issue"])
    render json: issue
  end

  def show
    @issue = Issue.find(params["id"])
    render
  end

  def index
    render json: Issue.order(:relevance).limit(20)
  end

  def edit
  end

  def update
    issue = Issue.update_attributes(params["issue"])
    render json: issue
  end

  def destroy
    render status: 405
  end
  
  def fix
    # TODO clean variables, control save action
    issue = Issue.find(params["id"])
    issue.fixed += 1
    issue.save
    redirect_to issue
  end
  
  def unfix
    issue = Issue.find(params["id"])
    issue.fixed -= 1
    issue.save
    redirect_to issue
  end

end

api/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

api/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
  end

  def create
    issue = Tag.create(params["issue"])
    render json: issue
  end

  def show
    @tag = Tag.find(params["id"])
    Rails.logger.info @tag.issues
    render
  end

  def index
    render json: Tag.limit(20)
  end

  def edit
  end

  def update
    tag = Tag.update_attributes(params["tag"])
    render json: tag
  end

  def destroy
    render status: 405
  end
end

api/app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
  def new
    if (user = User.where(twitter_user_id: params["user_id"]).first).nil?
      user = User.create(twitter_user_id: params["user_id"].to_i)
    end
    issue = Issue.new(
                      text: params["text"],
                      image_url: params["image_url"],
                      latitude: params["latitude"].to_f,
                      longitude: params["longitude"].to_f,
                      tweet_id: params["tweet_id"],
                      user_id: user.id
                      )

    unless params["hastags"].nil? 
      params["hashtags"].each do |hashtag|
        if (tag = Tag.where(title: tag).first).nil?
          tag = Tag.create(title: tag)
        end
        issue.add_tag(tag)
      end
    end

    if issue.save
      render json: "/issues/#{issue.id}", status: 201
    else
      render text: "Error", status: 400
    end
  end

  def reply
    unless (issue = give_relevance(params['reply_to_id'])).nil?
      reply = Reply.new(
                        issue_id: issue.id,
                        message: params["message"],
                        tweet_id: params["tweet_id"],
                        reply_to_id: params["reply_to_id"],
                        user_id: params["user_id"],
                        image_url: params["image_url"]
                        )

      if reply.save
        render text: "OK", status: 201
      else
        render text: reply.errors, status: 400
      end
    else
      render text: "Error", status: 400
    end
  end

  def rt
    unless (issue = give_relevance(params['tweet_id'])).nil?
      if issue.save
        render text: "OK", status: 201
      else
        render text: issue.errors, status: 400
      end
    else
      render text: "Error", status: 400
    end
  end

  private

  def give_relevance(tweet_id)
    unless (issue = Issue.where(tweet_id: tweet_id).first).nil?
      issue.relevance ||= 0
      issue.relevance += 1
      issue
    end
  end

end

api/app/helpers/application_helper.rb
module ApplicationHelper
end

api/app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

api/app/helpers/home_helper.rb
module HomeHelper
end

api/app/helpers/issues_helper.rb
module IssuesHelper
end

api/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

api/app/helpers/session_helper.rb
module SessionHelper
end

api/app/helpers/tags_helper.rb
module TagsHelper
end

api/app/helpers/twitter_helper.rb
module TwitterHelper
end

api/app/views/authentications/index.html.erb
<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You have signed in with these services:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider_name %></div>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>

<div class="clear"></div>

<% unless user_signed_in? %>
  <p>
    <strong>Don't use these services?</strong>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "sign in", new_user_session_path %> with a password.
  </p>
<% end %>

api/app/views/home/index.html.erb
<h1>Ombud</h1>
<%= image_tag("logo.png", class: "pull-right") %>
<p>Ombud es un sistema que actúa como <em>Ombudsman</em> entre tú y los entes estatales encargados de cuidar tu ciudad. Te ayuda a informarlos de problemas como calles en mal estado, basura, alumbrado público dañado o situaciones peligrosas en tu barrio.</p>
<p>La idea es catalogar la información y hacer llegar los reportes de incidentes a las entidades o personas que puedan darle una solución. Los datos generados son abiertos y usamos la tecnología de datos abiertos de OpenStreetMap para proveer geolocalizaci&oacute;n a la informaci&oacute;n.
</p>
<h3>Reportes</h3>
<% @issues.each do |issue| %>
  <p>
    <%= link_to issue.text, issue_path(issue) %>
  </p>
<% end %>

api/app/views/issues/show.html.erb
<div>
<h1>Reporte #<%= @issue.id %></h1>
<p><%= @issue.text %></p>

<% if @issue.latitude != 0  && @issue.longitude != 0 %>
<div id="mapdiv" style="height:500px; width: 500px;"></div>

<script>
    map = new OpenLayers.Map("mapdiv");
    map.addLayer(new OpenLayers.Layer.OSM());
    //-34.878842,-56.076877
    var lonLat = new OpenLayers.LonLat( <%= @issue.longitude %>, <%= @issue.latitude %> )
          .transform(
            new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
            map.getProjectionObject() // to Spherical Mercator Projection
          );
 
    var zoom=16;
 
    var markers = new OpenLayers.Layer.Markers( "Markers" );
    map.addLayer(markers);
 
    markers.addMarker(new OpenLayers.Marker(lonLat));
 
    map.setCenter (lonLat, zoom);
</script>
<% end %>

<h3>Foto</h3>

<% if @issue.image_url%>
<img src="<%= @issue.image_url %>"/>
<% end %>

<div class="issue-fix-panel">
  <%= link_to "fix", fix_issue_path(@issue) %>
  <%= link_to "unfix", unfix_issue_path(@issue) %>
  <p>
    <%= "Ranking: #{@issue.fixed}" %>
  </p>
</div>

add more info
reteew
reply
</div>

api/app/views/layouts/_header.html.erb
<!-- START HEADER -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="brand" href="/">OmbudUY</a>
      <div class="nav-collapse collapse">
        <!-- START LOGIN FORM -->
        <div class="navbar-text pull-right login-form">
        <% if user_signed_in? %>  
          Signed in as <%= current_user.email.blank? ? current_user.screenname  : current_user.email %>. Not you?  
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>  
          <%= form_for "user", :url => user_session_path do |f| %>
            <fieldset class="login-form">
              <div style="display: inline-block;">
                <%= f.text_field :email %>
                <%= f.password_field :password %>
              </div>
              <div style="display: inline-block;  ">
                <%= f.label :remember_me %>
                <%= f.check_box :remember_me %>
                <%= f.submit 'Sign in', :class => "button" %>
              </div>
              <div>
                <%= link_to  'Olvidaste tu password?', new_password_path('user')  %>
                <%= link_to new_user_registration_path, :id => 'lnk_registration' do %>
                <strong class="font-weight-bold">Registrate</strong>
                <% end %>
                <%= link_to "Sign in with Twitter", "/auth/twitter" %>
              </div>
            </fieldset>
          <% end %>
        <% end %>
        </div>
        <!-- END LOGIN FORM -->
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<!-- START HEADER -->

api/app/views/layouts/_sidebar.html.erb
<%= render_cell :tag_cloud, :display %>

<%= render_cell :open_issues, :display %>

api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ombud</title>
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css" media="screen" title="no title" />
    <link rel="stylesheet" href="/bootstrap/css/bootstrap-responsive.css" type="text/css" media="screen" title="no title" />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <script src="http://www.openlayers.org/api/OpenLayers.js"></script> 
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render :partial => '/layouts/header' %>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span4">
          <div class="well sidebar-nav">
            <%= render :partial => '/layouts/sidebar'%> 
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span8">
          <div class="hero-unit">
            <%= yield %>
          </div>
        </div><!--/span-->
      </div><!--/row-->
      
      <hr>
      
      <footer>
        <p>&copy; <a href="http://2012.desarrollandoamerica.org/">Desarrollando Am&eacute;rica 2012</a> | <a href="http://twitter.com/ombuduy">Ombud en Twitter</a></p>
      </footer>
      
    <div><!--/.fluid-container-->   
  </body>
</html>

api/app/views/tags/show.html.erb
<h2>Tag <%= @tag.title %></h2>
<% @tag.issues.each do |issue| %>
  <div style="border: 1px solid #000">
    <p><%= issue.text %></p>
  </div>
<% end %>